-- =============================================================================
-- Migration: 00001_initial_schema.sql
-- Real Estate CRM — Full schema converted from Prisma to Supabase PostgreSQL
--
-- Run order:
--   1. This file  (schema + enums + tables + indexes + triggers)
--   2. 00002_rls_policies.sql
--   3. 00003_indexes.sql
--
-- Notes:
-- • cuid() values are generated by the application layer (Prisma / nanoid).
--   We use text PKs to match the existing Prisma schema.
-- • auth.users is managed by Supabase Auth — we link via auth_user_id.
-- • All timestamps use timestamptz for timezone correctness.
-- =============================================================================

-- ─── Extensions ───────────────────────────────────────────────────────────────

create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

-- ─── Enums ────────────────────────────────────────────────────────────────────

create type plan_enum as enum (
  'FREE', 'STARTER', 'PROFESSIONAL', 'ENTERPRISE', 'TRIAL'
);

create type org_status_enum as enum (
  'ACTIVE', 'SUSPENDED', 'CANCELLED', 'TRIAL'
);

create type user_role_enum as enum (
  'SUPER_ADMIN', 'COMPANY_ADMIN', 'SALES_MANAGER', 'SALES_AGENT',
  'MARKETING_MANAGER', 'ACCOUNTANT', 'PROPERTY_MANAGER', 'VIEWER'
);

create type user_status_enum as enum (
  'ACTIVE', 'INACTIVE', 'INVITED', 'SUSPENDED'
);

create type lead_status_enum as enum (
  'NEW', 'CONTACTED', 'QUALIFIED', 'UNQUALIFIED',
  'VIEWING_SCHEDULED', 'VIEWING_COMPLETED', 'NEGOTIATION',
  'RESERVED', 'WON', 'LOST'
);

create type lead_temperature_enum as enum (
  'HOT', 'WARM', 'COLD'
);

create type lead_source_enum as enum (
  'WEBSITE', 'FACEBOOK', 'INSTAGRAM', 'WHATSAPP', 'GOOGLE_ADS',
  'PROPERTY_PORTAL', 'REFERRAL', 'PHONE', 'WALK_IN', 'MANUAL', 'IMPORT', 'OTHER'
);

create type purchase_purpose_enum as enum (
  'OWN_USE', 'INVESTMENT', 'RENTAL', 'RESALE', 'UNDECIDED'
);

create type financing_preference_enum as enum (
  'CASH', 'MORTGAGE', 'INSTALLMENT', 'UNDECIDED'
);

create type property_type_enum as enum (
  'RESIDENTIAL', 'COMMERCIAL', 'ADMINISTRATIVE', 'RETAIL', 'LAND', 'OTHER'
);

create type unit_type_enum as enum (
  'APARTMENT', 'VILLA', 'TOWNHOUSE', 'DUPLEX', 'PENTHOUSE', 'STUDIO',
  'OFFICE', 'SHOP', 'WAREHOUSE', 'LAND_PLOT', 'OTHER'
);

create type unit_status_enum as enum (
  'AVAILABLE', 'ON_HOLD', 'RESERVED', 'CONTRACTED', 'SOLD', 'RENTED', 'UNAVAILABLE'
);

create type unit_finishing_enum as enum (
  'UNFINISHED', 'SEMI_FINISHED', 'FULLY_FINISHED', 'FURNISHED', 'SUPER_LUX'
);

create type project_status_enum as enum (
  'PLANNING', 'UNDER_CONSTRUCTION', 'READY', 'COMPLETED', 'ON_HOLD'
);

create type viewing_status_enum as enum (
  'SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'RESCHEDULED'
);

create type offer_status_enum as enum (
  'DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'WITHDRAWN'
);

create type reservation_status_enum as enum (
  'ACTIVE', 'EXPIRED', 'CANCELLED', 'CONVERTED'
);

create type deal_status_enum as enum (
  'DRAFT', 'RESERVED', 'CONTRACTED', 'PARTIALLY_PAID', 'COMPLETED', 'CANCELLED'
);

create type pipeline_stage_enum as enum (
  'NEW_LEAD', 'CONTACTED', 'QUALIFIED', 'PROPERTY_MATCHING',
  'VIEWING_SCHEDULED', 'VIEWING_COMPLETED', 'OFFER', 'NEGOTIATION',
  'RESERVATION', 'CONTRACT', 'CLOSED_WON', 'CLOSED_LOST'
);

create type installment_status_enum as enum (
  'UPCOMING', 'DUE', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED'
);

create type payment_method_enum as enum (
  'CASH', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'OTHER'
);

create type payment_status_enum as enum (
  'PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED'
);

create type commission_status_enum as enum (
  'PENDING', 'APPROVED', 'PAYABLE', 'PAID', 'CANCELLED'
);

create type task_priority_enum as enum (
  'LOW', 'MEDIUM', 'HIGH', 'URGENT'
);

create type task_status_enum as enum (
  'TODO', 'IN_PROGRESS', 'DONE', 'CANCELLED'
);

create type communication_channel_enum as enum (
  'WHATSAPP', 'EMAIL', 'PHONE', 'IN_PERSON', 'SMS', 'OTHER'
);

create type communication_direction_enum as enum (
  'INBOUND', 'OUTBOUND'
);

create type notification_type_enum as enum (
  'LEAD_ASSIGNED', 'LEAD_STATUS_CHANGED', 'VIEWING_SCHEDULED',
  'VIEWING_REMINDER', 'TASK_DUE', 'TASK_OVERDUE', 'INSTALLMENT_DUE',
  'INSTALLMENT_OVERDUE', 'RESERVATION_EXPIRING', 'DEAL_STAGE_CHANGED',
  'COMMISSION_APPROVED', 'SYSTEM'
);

create type assignment_strategy_enum as enum (
  'ROUND_ROBIN', 'LEAST_ACTIVE_LEADS', 'GEOGRAPHIC', 'TEAM', 'MANUAL'
);

create type audit_action_enum as enum (
  'CREATE', 'UPDATE', 'DELETE', 'STATUS_CHANGE', 'ASSIGN', 'LOGIN', 'LOGOUT'
);

create type document_related_type_enum as enum (
  'LEAD', 'CUSTOMER', 'DEAL', 'RESERVATION', 'UNIT', 'PROJECT'
);

-- =============================================================================
-- ORGANIZATION (TENANT ROOT)
-- =============================================================================

create table organizations (
  id            text        primary key,
  name          text        not null,
  slug          text        not null unique,
  plan          plan_enum   not null default 'TRIAL',
  status        org_status_enum not null default 'TRIAL',
  logo_url      text,
  website       text,
  phone         text,
  email         text,
  address       text,
  country       text,
  city          text,
  currency      text        not null default 'AED',
  timezone      text        not null default 'Asia/Dubai',
  settings      jsonb       not null default '{}',
  trial_ends_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- =============================================================================
-- USERS & IDENTITY
-- =============================================================================

create table users (
  id              text           primary key,
  -- Link to Supabase Auth user (auth.users.id). NULL until migrated from custom JWT.
  auth_user_id    uuid           unique references auth.users(id) on delete set null,
  organization_id text           not null references organizations(id) on delete cascade,
  email           text           not null,
  -- password_hash kept for migration period; nulled out once Supabase Auth active for this user
  password_hash   text,
  role            user_role_enum not null,
  status          user_status_enum not null default 'INVITED',
  email_verified  boolean        not null default false,
  last_login_at   timestamptz,
  last_seen_at    timestamptz,
  created_at      timestamptz    not null default now(),
  updated_at      timestamptz    not null default now(),
  unique (organization_id, email)
);

create table user_profiles (
  id          text  primary key,
  user_id     text  not null unique references users(id) on delete cascade,
  first_name  text  not null,
  last_name   text  not null,
  phone       text,
  avatar_url  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Supabase Auth handles sessions; this table is kept for legacy refresh token
-- tracking during the transition period. Can be dropped after Phase E complete.
create table refresh_tokens (
  id         text  primary key,
  user_id    text  not null references users(id) on delete cascade,
  token_hash text  not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- =============================================================================
-- TEAMS
-- =============================================================================

create table teams (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  name            text  not null,
  description     text,
  manager_id      text  references users(id) on delete set null,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table team_members (
  id         text  primary key,
  team_id    text  not null references teams(id) on delete cascade,
  user_id    text  not null references users(id) on delete cascade,
  joined_at  timestamptz not null default now(),
  unique (team_id, user_id)
);

-- =============================================================================
-- CAMPAIGNS
-- =============================================================================

create table campaigns (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  name            text  not null,
  description     text,
  source          lead_source_enum,
  channel         text,
  budget          numeric(15,2),
  spent           numeric(15,2) default 0,
  start_date      timestamptz,
  end_date        timestamptz,
  is_active       boolean not null default true,
  metadata        jsonb   not null default '{}',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =============================================================================
-- LEADS
-- =============================================================================

create table leads (
  id                    text  primary key,
  organization_id       text  not null references organizations(id) on delete cascade,
  assigned_agent_id     text  references users(id) on delete set null,
  team_id               text  references teams(id) on delete set null,
  campaign_id           text  references campaigns(id) on delete set null,

  full_name             text  not null,
  phone                 text,
  whatsapp              text,
  email                 text,
  nationality           text,
  language              text,

  status                lead_status_enum      not null default 'NEW',
  temperature           lead_temperature_enum not null default 'WARM',
  source                lead_source_enum      not null default 'MANUAL',
  lead_score            integer not null default 0,

  budget_min            numeric(15,2),
  budget_max            numeric(15,2),
  preferred_type        unit_type_enum,
  preferred_location    text,
  bedrooms              integer,
  area_min              numeric(10,2),
  area_max              numeric(10,2),
  purchase_purpose      purchase_purpose_enum,
  financing_preference  financing_preference_enum,

  notes                 text,
  is_archived           boolean not null default false,
  next_followup_at      timestamptz,
  last_contacted_at     timestamptz,
  converted_at          timestamptz,
  lost_reason           text,
  metadata              jsonb not null default '{}',

  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create table lead_activities (
  id              text  primary key,
  lead_id         text  not null references leads(id) on delete cascade,
  organization_id text  not null references organizations(id) on delete cascade,
  actor_id        text  references users(id) on delete set null,
  type            text  not null,
  payload         jsonb not null default '{}',
  created_at      timestamptz not null default now()
);

create table lead_saved_units (
  id         text  primary key,
  lead_id    text  not null references leads(id) on delete cascade,
  unit_id    text  not null,   -- FK added after units table created
  created_at timestamptz not null default now(),
  unique (lead_id, unit_id)
);

-- =============================================================================
-- CUSTOMERS
-- =============================================================================

create table customers (
  id                  text  primary key,
  organization_id     text  not null references organizations(id) on delete cascade,
  lead_id             text  references leads(id) on delete set null,
  assigned_agent_id   text  references users(id) on delete set null,

  full_name           text  not null,
  phone               text,
  whatsapp            text,
  email               text,
  nationality         text,
  id_number           text,
  id_type             text,
  date_of_birth       date,
  address             text,
  notes               text,
  metadata            jsonb not null default '{}',

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table customer_saved_units (
  id          text  primary key,
  customer_id text  not null references customers(id) on delete cascade,
  unit_id     text  not null,   -- FK added after units table created
  created_at  timestamptz not null default now(),
  unique (customer_id, unit_id)
);

-- =============================================================================
-- PROPERTY HIERARCHY
-- =============================================================================

create table projects (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  name            text  not null,
  description     text,
  developer       text,
  location        text,
  address         text,
  city            text,
  country         text,
  lat             numeric(10,7),
  lng             numeric(10,7),
  status          project_status_enum not null default 'PLANNING',
  property_type   property_type_enum,
  total_units     integer not null default 0,
  available_units integer not null default 0,
  start_date      date,
  expected_delivery date,
  website         text,
  brochure_url    text,
  amenities       text[],
  metadata        jsonb not null default '{}',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table buildings (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  project_id      text  not null references projects(id) on delete cascade,
  name            text  not null,
  floors_count    integer not null default 1,
  description     text,
  metadata        jsonb not null default '{}',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table floors (
  id           text  primary key,
  building_id  text  not null references buildings(id) on delete cascade,
  floor_number integer not null,
  description  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table units (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  project_id      text  not null references projects(id) on delete cascade,
  building_id     text  references buildings(id) on delete set null,
  floor_id        text  references floors(id) on delete set null,

  unit_number     text  not null,
  unit_type       unit_type_enum  not null default 'APARTMENT',
  status          unit_status_enum not null default 'AVAILABLE',
  finishing       unit_finishing_enum,

  area            numeric(10,2),
  bedrooms        integer not null default 0,
  bathrooms       integer not null default 0,
  price           numeric(15,2) not null,
  price_per_sqm   numeric(15,2),

  floor_number    integer,
  direction       text,
  view            text,
  has_parking     boolean not null default false,
  parking_spaces  integer not null default 0,
  has_garden      boolean not null default false,

  delivery_date   date,
  description     text,
  images          text[],
  floor_plan_url  text,
  metadata        jsonb not null default '{}',

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Add FK constraints for saved units (deferred until units table exists)
alter table lead_saved_units
  add constraint lead_saved_units_unit_id_fkey
  foreign key (unit_id) references units(id) on delete cascade;

alter table customer_saved_units
  add constraint customer_saved_units_unit_id_fkey
  foreign key (unit_id) references units(id) on delete cascade;

create table payment_plan_templates (
  id                          text  primary key,
  project_id                  text  not null references projects(id) on delete cascade,
  name                        text  not null,
  description                 text,
  down_payment_pct            numeric(5,2) not null,
  installment_count           integer not null,
  installment_frequency_months integer not null default 1,
  handover_pct                numeric(5,2) not null default 0,
  is_active                   boolean not null default true,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

-- =============================================================================
-- VIEWINGS
-- =============================================================================

create table viewings (
  id               text  primary key,
  organization_id  text  not null references organizations(id) on delete cascade,
  lead_id          text  references leads(id) on delete set null,
  customer_id      text  references customers(id) on delete set null,
  unit_id          text  references units(id) on delete set null,
  agent_id         text  not null references users(id),

  scheduled_at     timestamptz not null,
  end_at           timestamptz,
  location         text,
  status           viewing_status_enum not null default 'SCHEDULED',

  customer_feedback text,
  agent_feedback    text,
  outcome           text,
  next_action       text,
  notes             text,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- =============================================================================
-- OFFERS
-- =============================================================================

create table offers (
  id                text  primary key,
  organization_id   text  not null references organizations(id) on delete cascade,
  lead_id           text  references leads(id) on delete set null,
  customer_id       text  references customers(id) on delete set null,
  unit_id           text  not null references units(id),
  agent_id          text  not null references users(id),

  original_price    numeric(15,2) not null,
  offered_price     numeric(15,2) not null,
  discount          numeric(15,2) not null default 0,
  discount_pct      numeric(5,2)  not null default 0,
  down_payment      numeric(15,2),
  installment_count integer,
  payment_notes     text,
  status            offer_status_enum not null default 'DRAFT',
  expires_at        timestamptz,
  notes             text,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- =============================================================================
-- RESERVATIONS
-- =============================================================================

create table reservations (
  id                  text  primary key,
  organization_id     text  not null references organizations(id) on delete cascade,
  unit_id             text  not null references units(id),
  customer_id         text  not null references customers(id),
  agent_id            text  not null references users(id),
  deal_id             text,   -- FK to deals added below (circular ref workaround)

  reservation_date    timestamptz not null default now(),
  expires_at          timestamptz,
  reservation_amount  numeric(15,2),
  status              reservation_status_enum not null default 'ACTIVE',
  payment_status      text,
  document_url        text,
  notes               text,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),

  -- Enforce one active reservation per unit
  constraint reservations_unit_active_unique
    unique (unit_id, status)
    deferrable initially deferred
);

-- =============================================================================
-- DEALS
-- =============================================================================

create table deals (
  id                  text  primary key,
  organization_id     text  not null references organizations(id) on delete cascade,
  customer_id         text  not null references customers(id),
  unit_id             text  not null references units(id),
  agent_id            text  not null references users(id),
  manager_id          text  references users(id),

  deal_number         text  not null,
  title               text,
  sale_price          numeric(15,2) not null,
  discount            numeric(15,2) not null default 0,
  net_sale_value      numeric(15,2) not null,

  status              deal_status_enum not null default 'DRAFT',
  pipeline_stage      pipeline_stage_enum not null default 'RESERVATION',

  contract_date       timestamptz,
  closing_date        timestamptz,
  expected_close_date timestamptz,
  probability         integer not null default 70,
  notes               text,
  metadata            jsonb not null default '{}',

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- Now add reservation → deal FK
alter table reservations
  add constraint reservations_deal_id_fkey
  foreign key (deal_id) references deals(id) on delete set null;

-- =============================================================================
-- PAYMENT PLANS & INSTALLMENTS
-- =============================================================================

create table payment_plans (
  id                  text  primary key,
  deal_id             text  not null unique references deals(id) on delete cascade,
  organization_id     text  not null references organizations(id) on delete cascade,

  total_amount        numeric(15,2) not null,
  down_payment        numeric(15,2) not null,
  remaining_amount    numeric(15,2) not null,
  installment_count   integer not null,
  installment_amount  numeric(15,2) not null,
  handover_amount     numeric(15,2) not null default 0,
  frequency_months    integer not null default 1,
  start_date          timestamptz not null,
  notes               text,
  status              text not null default 'ACTIVE',

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create table installments (
  id               text  primary key,
  payment_plan_id  text  not null references payment_plans(id) on delete cascade,
  deal_id          text  not null references deals(id) on delete cascade,
  organization_id  text  not null references organizations(id) on delete cascade,

  due_date         timestamptz not null,
  amount           numeric(15,2) not null,
  paid_amount      numeric(15,2) not null default 0,
  remaining_amount numeric(15,2) not null,
  status           installment_status_enum not null default 'UPCOMING',
  paid_at          timestamptz,
  overdue_days     integer not null default 0,
  notes            text,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- =============================================================================
-- PAYMENTS
-- =============================================================================

create table payments (
  id               text  primary key,
  organization_id  text  not null references organizations(id) on delete cascade,
  deal_id          text  not null references deals(id),
  installment_id   text  references installments(id),
  customer_id      text  references customers(id),

  amount           numeric(15,2) not null,
  currency         text not null default 'AED',
  method           payment_method_enum not null default 'BANK_TRANSFER',
  status           payment_status_enum not null default 'COMPLETED',

  reference_number text,
  receipt_url      text,
  paid_at          timestamptz not null,
  notes            text,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

-- =============================================================================
-- COMMISSIONS
-- =============================================================================

create table commission_rules (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  name            text  not null,
  agent_rate      numeric(5,2) not null,
  manager_rate    numeric(5,2) not null default 0,
  is_default      boolean not null default false,
  conditions      jsonb not null default '{}',
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table commissions (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  deal_id         text  not null references deals(id),
  agent_id        text  not null references users(id),
  manager_id      text  references users(id),
  rule_id         text  references commission_rules(id),

  agent_rate      numeric(5,2) not null,
  manager_rate    numeric(5,2) not null default 0,
  base_amount     numeric(15,2) not null,
  agent_amount    numeric(15,2) not null,
  manager_amount  numeric(15,2) not null default 0,
  total_amount    numeric(15,2) not null,
  status          commission_status_enum not null default 'PENDING',
  approved_at     timestamptz,
  paid_at         timestamptz,
  notes           text,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =============================================================================
-- TASKS
-- =============================================================================

create table tasks (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  creator_id      text  references users(id) on delete set null,
  assignee_id     text  references users(id) on delete set null,
  related_type    text,
  related_id      text,
  title           text  not null,
  description     text,
  due_at          timestamptz,
  priority        task_priority_enum not null default 'MEDIUM',
  status          task_status_enum   not null default 'TODO',
  completed_at    timestamptz,
  metadata        jsonb not null default '{}',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =============================================================================
-- NOTIFICATIONS
-- =============================================================================

create table notifications (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  user_id         text  not null references users(id) on delete cascade,
  type            notification_type_enum not null,
  title           text  not null,
  body            text,
  payload         jsonb not null default '{}',
  is_read         boolean not null default false,
  read_at         timestamptz,
  created_at      timestamptz not null default now()
);

-- =============================================================================
-- COMMUNICATIONS
-- =============================================================================

create table communications (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  lead_id         text  references leads(id) on delete set null,
  customer_id     text  references customers(id) on delete set null,
  agent_id        text  references users(id) on delete set null,

  channel         communication_channel_enum    not null,
  direction       communication_direction_enum  not null default 'OUTBOUND',
  content         text,
  status          text,
  external_id     text,    -- WhatsApp message ID, email message ID, etc.
  metadata        jsonb not null default '{}',
  sent_at         timestamptz not null default now(),

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =============================================================================
-- DOCUMENTS
-- =============================================================================

create table documents (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  uploaded_by_id  text  references users(id) on delete set null,
  related_type    document_related_type_enum not null,
  related_id      text  not null,

  name            text  not null,
  original_name   text  not null,
  mime_type       text  not null,
  size_bytes      integer not null,

  -- Supabase Storage path (replaces S3 storage_key)
  storage_path    text  not null,
  bucket          text  not null default 'recrm-documents',

  is_public       boolean not null default false,
  metadata        jsonb not null default '{}',

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =============================================================================
-- AUDIT LOGS
-- =============================================================================

create table audit_logs (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  actor_id        text  references users(id) on delete set null,
  action          audit_action_enum not null,
  entity_type     text  not null,
  entity_id       text  not null,
  before          jsonb,
  after           jsonb,
  ip_address      text,
  user_agent      text,
  metadata        jsonb not null default '{}',
  created_at      timestamptz not null default now()
);

-- =============================================================================
-- CONFIGURATION TABLES
-- =============================================================================

create table lead_status_configs (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  status          text  not null,
  label           text  not null,
  color           text,
  position        integer not null default 0,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table lead_scoring_rules (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  signal          text  not null,
  points          integer not null,
  description     text,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table pipeline_stage_configs (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  stage           pipeline_stage_enum not null,
  label           text  not null,
  color           text,
  position        integer not null default 0,
  probability     integer not null default 0,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table assignment_rules (
  id              text  primary key,
  organization_id text  not null references organizations(id) on delete cascade,
  name            text  not null,
  strategy        assignment_strategy_enum not null default 'ROUND_ROBIN',
  team_id         text  references teams(id) on delete set null,
  conditions      jsonb not null default '{}',
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =============================================================================
-- UPDATED_AT TRIGGERS
-- =============================================================================

create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Apply to every table with updated_at
do $$
declare
  t text;
begin
  foreach t in array array[
    'organizations', 'users', 'user_profiles', 'teams', 'campaigns',
    'leads', 'customers', 'projects', 'buildings', 'floors', 'units',
    'payment_plan_templates', 'viewings', 'offers', 'reservations', 'deals',
    'payment_plans', 'installments', 'payments', 'commission_rules',
    'commissions', 'tasks', 'communications', 'documents',
    'lead_status_configs', 'lead_scoring_rules', 'pipeline_stage_configs',
    'assignment_rules'
  ]
  loop
    execute format(
      'create trigger set_%I_updated_at
       before update on %I
       for each row execute function set_updated_at()',
      t, t
    );
  end loop;
end;
$$;
